configfile: "config/config.yaml"	

rule all:
    input:
        #expand("results/snp-count/{sample}_allSNPcount.tsv", sample=config["Barcodes"])
        "results/snp-count/WT_E85_SNPcount.tsv"


# In case of multiple libraries, combine aggregated data
rule combine_aggregated_data:
    input:
        expand("results/snp-count/{sample}_allSNPcount.tsv", sample=config["Samples"])
    output:
        "results/snp-count/WT_E85_SNPcount.tsv"
    log:
        "logs/combine_aggregated_data/WT_E85.log"
    shell:
        """
        awk '{{printf $1 "-" ARGIND "\\t" $2 "\\t" $3 "\\n" }}' {input} > {output} 2> {log}
        """

# Deconvolute single cells and assign to embryos
#rule deconvolute_aggregated_data:
#    input:
#        "results/splitreads/WT_E85_SNPcount.tsv"
#    output:
#        ""
#    conda:
#    "envs/r.yaml"
#    shell:
#        """
#        Rscript-3.6.3 /project/Mouse_Embryos/scripts/cell2embryo.R {input} results/cell2embryo/ WT_E85
#        """

include: "rules/module1.smk"
include: "rules/module2.smk"