## Info
## Its mandatory to specify an ID
ID: "WT_E85"
# The embryo number gets calculated in the RScript "cell2embryo" when its set to zero in the config file
embryo_nr: 0

## data
# Barcodes should be named [ID]__barcodes.tsv.gz and stored in the respective sample folder
Barcodes:
  AM-RNA-496: "resources/barcodes/AM-RNA-496/"
  AM-RNA-497: "resources/barcodes/AM-RNA-497/"

# Samples should be named [sample]__R1_001.fastq.gz and [sample]__R2_001.fastq.gz respectively
Samples:
  AM-RNA-496: "resources/data/mpimg_L20527-1_AM-RNA-496"
  AM-RNA-497: "resources/data/mpimg_L20527-1_AM-RNA-497"

## previously generated files
# genome_dir is the directory where the previously generated genome indices are stored (needed for alignment)
genome_dir_path: "/project/bioinf_meissner/src/SNPsplit/SNPsplit_v0.3.2" 
# the following three files are needed while preparing the alignment for deconvolution
all_snps_path: "resources/snps/all_SNPs_CAST_EiJ_GRCm38.txt.gz" 
all_snps_bed_path: "resources/snps/all_SNPs_CAST_EiJ_GRCm38.bed"
SNPwhite_list_path: "resources/scRNA/WT_SNP_white.list.tsv"
# matrix_dir contains three matrices needed by the RScript "sex2embryo" for the determination of the sex 
matrix_dir_path: "resources/barcodes/matrix/" 